version: "3.9"

services:
  nuxt-app:
    container_name: nuxt-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3008:3000"
    volumes:
      - ./:/var/www/app
    tty: true